apiVersion: v1
kind: Service
metadata:
  name: api-doctor-service
spec:
  selector:
    app: api-doctor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30859
  type: LoadBalancer