apiVersion: v1
kind: Service
metadata:
  name: api-auth-config-service
  namespace: healthmed
spec:
  selector:
    app: api-auth
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30851
  type: NodePort