apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-auth-config
  namespace: healthmed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-auth
  template:
    metadata:
      labels:
        app: api-auth
    spec:
      containers:
        - name: apiauth
          image: ciroa/health-med:HealthMed.Auth.API-latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-auth-config
            - secretRef:
                name: api-auth-secret
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10