apiVersion: v1
kind: Service
metadata:
  name: api-auth-config-service
spec:
  selector:
    app: api-auth-config
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30416
  type: NodePort