apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-doctor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-doctor
  template:
    metadata:
      labels:
        app: api-doctor
    spec:
      containers:
        - name: apimed
          image: ciroa/health-med:HealthMed.Medico.API-latest
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__postgres
              value: "Server=postgres-service;Port=5432;Database=HealthMed;User Id=admin;Password=$(POSTGRES_PASSWORD);"
          envFrom:
            - configMapRef:
                name: api-doctor-config
            - secretRef:
                name: postgres-secret
