apiVersion: v1
kind: Service
metadata:
  name: api-consultation-service
spec:
  selector:
    app: api-consultation
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30852
  type: NodePort