apiVersion: v1
kind: Service
metadata:
  name: api-agenda-service
spec:
  selector:
    app: api-agenda
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30856
  type: LoadBalancer