apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-med-gateway
  template:
    metadata:
      labels:
        app: health-med-gateway
    spec:
      containers:
        - name: apigateway
          image: ciroa/health-med:HealthMed.Gateway.API-latest
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__postgres
              value: "Server=postgres-service;Port=5432;Database=HealthMed;User Id=admin;Password=$(POSTGRES_PASSWORD);"
          envFrom:
            - configMapRef:
                name: api-gateway-config
            - secretRef:
                name: postgres-secret