apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: healthmed
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/grafana"