apiVersion: v1
kind: Service
metadata:
  name: infra-consumer-consultation-service
spec:
  selector:
    app: infra-consumer-consultation
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30903
  type: NodePort
