apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-consumer-consultation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: infra-consumer-consultation
  template:
    metadata:
      labels:
        app: infra-consumer-consultation
    spec:
      containers:
        - name: rabbitmq-consumer-consulta
          image: ciroa/health-med:HealthMed.Consultation.Infra.Consumer-latest
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__postgres
              value: "Server=postgres-service;Port=5432;Database=HealthMed;User Id=admin;Password=$(POSTGRES_PASSWORD);"
          envFrom:
            - configMapRef:
                name: infra-consumer-consultation-config
            - secretRef:
                name: postgres-secret