apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-consumer-patient
  namespace: healthmed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-consumer-patient
  template:
    metadata:
      labels:
        app: infra-consumer-patient
    spec:
      containers:
        - name: consumer-patient
          image: ciroa/health-med:RabbitMQ.Consumer.Paciente-latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: infra-consumer-patient-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"