apiVersion: v1
kind: Service
metadata:
  name: infra-consumer-patient-service
  namespace: healthmed
spec:
  selector:
    app: infra-consumer-patient
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
