apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-consumer-consultation
  namespace: healthmed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-consumer-consultation
  template:
    metadata:
      labels:
        app: infra-consumer-consultation
    spec:
      containers:
        - name: consumer-consultation
          image: ciroa/health-med:HealthMed.Consultation.Infra.Consumer-latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: infra-consumer-consultation-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"