apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  namespace: healthmed
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/rabbitmq"