FROM prom/prometheus:latest

# Certifique-se de que o arquivo existe neste caminho local
COPY configs/prometheus.yml /etc/prometheus/prometheus.yml

# Comando de entrada padrão
CMD [ "--config.file=/etc/prometheus/prometheus.yml" ]